CBTeam-Mvc/CBTeam-Mvc/Models/ErrorViewModel.cs
namespace CBTeam_Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CBTeam-Mvc/CBTeam-Mvc/Models/ProviderModel.cs
namespace CBTeam_Mvc.Models
{
    public class ProviderModel
    {
        public int Id { get; set; } 
        public string ProviderName { get; set; }   
        public string? Locality { get; set; }
    }
}

CBTeam-Mvc/CBTeam-Mvc/Controllers/HomeController.cs
using CBTeam_Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CBTeam_Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CBTeam-Mvc/CBTeam-Mvc/Controllers/ProviderController.cs
using CBTeam.WCFClass;
using CBTeam_Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using System.Collections.Generic;
using System.Linq;

namespace CBTeam_Mvc.Controllers
{
    [Microsoft.AspNetCore.Mvc.Route("providers")]
    public class ProviderController : Controller
    {
        private List<ProviderModel> GetAllProviders()
        {
            return new List<ProviderModel>
            {
                new ProviderModel { Id = 1, ProviderName = "Piamontesa S.A", Locality = "Canada 260-Las Varillas" },
                new ProviderModel { Id = 2, ProviderName = "Paladinni S.A", Locality = "Libertad 883-La Plata" },
                new ProviderModel { Id = 3, ProviderName = "La Casona S.R.L", Locality = "Venezuela 223 -Buenos Aires" },
                new ProviderModel { Id = 4, ProviderName = "Las Moras S.A", Locality = "Jose Hernandez 221-San Francisco" },
                new ProviderModel { Id = 5, ProviderName = "Friar S.R.L", Locality = "Hipolito Irigoyen-San Luis" }
            };
        }

        [HttpGet]
        [Route("")]
        public IActionResult GetProviderList()
        {
            var providers = GetAllProviders();
            return View("Index", providers);
        }

        [HttpGet]
        [Route("SearchByName")]
        public IActionResult SearchByName(string Nombre)
        {
            var providers = GetAllProviders();
            var filteredProviders = providers.Where(p => p.ProviderName.Contains(Nombre)).ToList();
            return PartialView("_ProviderList", filteredProviders);
        }

        [HttpGet]
        [Route("GetAddressByName")]
        public ActionResult GetAddressByName(string searchName)
        {
            var service = new ServiceClient();
            List<Address> address = service.GetAddress().ToList();
            var filteredAddress =address.Where(a => a.AddressName.Contains(searchName)).ToList();
            return View("_ProviderAddress", filteredAddress);
        }
    }
}

CBTeam-Mvc/CBTeam-Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CBTeam-Mvc/CBTeam-Mvc/Views/Provider/Index.cshtml
@model List<CBTeam_Mvc.Models.ProviderModel>;
@{
}

<h2>Empresas Mayoristas</h2>
<div class="form-group">
    @using (Html.BeginForm("SearchByName", "Provider", FormMethod.Get))
    {
        <input type="text" id="searchInput" name="Nombre" />
        <div id="sugerencia"></div>
        <button type="submit">Buscar</button>
    }
</div>
<button id="showProviderListButton">Mostrar Lista</button>

<div id="providerList" style="display: none;">
    <ul>
        @foreach (var provider in Model)
        {
            <li>@provider.Id - @provider.ProviderName - @provider.Locality</li>
        }
    </ul>
</div>

@using (Html.BeginForm("GetAddressByName", "Provider", FormMethod.Get))
{
    <input type="text" id="searchInputAddress" name="searchName" />
    <div id="sugerenciaAddress"></div>
    <button type="submit">Buscar</button>
}

<div id="direccionContainer" style="display: none;"></div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("showProviderListButton").addEventListener("click", function () {
            var providerList = document.getElementById("providerList");
            if (providerList.style.display === "none" || providerList.style.display === "") {
                providerList.style.display = "block";
            } else {
                providerList.style.display = "none";
            }
        });

        var searchInput = document.getElementById("searchInput");
        var sugerencia = document.getElementById("sugerencia");

        searchInput.addEventListener("input", function () {
            var inputValue = searchInput.value.trim();

            if (inputValue.length >= 3) {
                $.ajax({
                    url: "/Provider/SearchByName",
                    type: "GET",
                    data: { Nombre: inputValue },
                    success: function (data) {
                        sugerencia.innerHTML = "";

                        data.forEach(function (provider) {
                            var divSugerencia = document.createElement("div");
                            divSugerencia.textContent = provider.ProviderName;

                            divSugerencia.addEventListener("click", function () {
                                searchInput.value = provider.ProviderName;
                                sugerencia.innerHTML = "";
                            });

                            sugerencia.appendChild(divSugerencia);
                        });
                    }
                });
            } else {
                sugerencia.innerHTML = "";
            }
        });
     
       
        var searchInputAddress = document.getElementById("searchInputAddress");
        var sugerenciaAddress = document.getElementById("sugerenciaAddress");

        searchInputAddress.addEventListener("input", function () {
            var inputValue = searchInputAddress.value.trim();

                $.ajax({
                    url: "/Provider/GetAddressByName",
                    type: "GET",
                    data: { searchName: inputValue }, 
                    success: function (addresses) {
                        var direccionContainer = document.getElementById("direccionContainer");
                        direccionContainer.innerHTML = "";
                        var direccionUl = document.createElement("ul");

                        addresses.forEach(function (address) {
                            var direccionLi = document.createElement("li");
                            direccionLi.textContent = address.AddressName + " " + address.AddressNumber;
                            direccionUl.appendChild(direccionLi);
                        });

                        direccionContainer.appendChild(direccionUl);
                        direccionContainer.style.display = "block";
                    },
                });           
        });
    });
</script>

CBTeam-Mvc/CBTeam-Mvc/Views/Provider/_ProviderAddress.cshtml
@model List<CBTeam.WCFClass.Address>

<h4>Dirección:</h4>
<div id="direccionContainer">
    <ul>
        @foreach (var address in Model)
        {
            <li>@address.AddressName - @address.AddressNumber</li>
        }
    </ul>
</div>

CBTeam-Mvc/CBTeam-Mvc/Views/Provider/_ProviderList.cshtml
@model List<CBTeam_Mvc.Models.ProviderModel>

<h4>Resultados de la búsqueda:</h4>
<ul>
    @foreach (var provider in Model)
    {
        <li>@provider.Id - @provider.ProviderName - @provider.Locality</li>
    }
</ul>

CBTeam-Mvc/CBTeam-Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CBTeam_Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CBTeam_Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CBTeam_Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Provider" asp-action="GetProviderList">Provider</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CBTeam_Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>